data:
  path: 'data/dataset/sequences/09'  # path to dataset for evaluation
  height: 192
  width: 640
model:
  path: 'data/models/RGB+Depth_multi_layer'  # path to models for evaluation
  type: 'multi_layer'  # select from ['early', 'middle', 'late', 'multi-layer']
output:
  path: 'data/outputs'  # path for saving outputs
  save_depth: False
