from .early_fusion import create_posenet_early
from .late_fusion import create_posenet_late
from .middle_fusion import create_posenet_middle
from .multi_layer_fusion import create_posenet_multi_layer
